export const FETCH_FINISH = 'FETCH_FINISH';

export const ADD_SUCCESS = 'ADD_SUCCESS';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const RESET_MESSAGE = 'RESET_MESSAGE';
